# Generated by Django 4.1.6 on 2023-02-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_delete_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('link_photo', models.CharField(max_length=255)),
                ('brief', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
