# Generated by Django 4.1.6 on 2023-02-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_product_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
